import importlib.util
import ast
import hashlib
import json
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "packages" / "k1-control-v1" / "start-sequence-owner-v1"


def load_verifier():
    spec = importlib.util.spec_from_file_location("start_sequence_owner_v1", PACKAGE / "verify_candidate.py")
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def load_module(name, filename):
    package_path = str(PACKAGE)
    if package_path not in sys.path:
        sys.path.insert(0, package_path)
    spec = importlib.util.spec_from_file_location(name, PACKAGE / filename)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


class StartSequenceOwnerV1Tests(unittest.TestCase):
    def test_candidate_is_preflight_qualified_and_not_authorized(self):
        result = load_verifier().verify()
        self.assertEqual("START_SEQUENCE_OWNER_V1_PREFLIGHT_QUALIFIED_OK", result["status"])
        self.assertEqual(1, result["g28_xy_only"])
        self.assertEqual(1, result["accurate_z_references"])
        self.assertEqual(0, result["automatic_brush_commands"])
        self.assertEqual(0, result["mesh_calibration_commands"])
        self.assertEqual(0, result["cfs_effect_commands"])
        self.assertTrue(result["deployment_candidate"])
        self.assertEqual("BLOCKED_NO_ENGAGED_T1A", result["physical_trial"])
        self.assertEqual("8/8", result["watchdog_scenarios"])
        self.assertEqual(300, result["manual_clean_token_validity_s"])

    def test_contract_keeps_only_the_proven_t1a_branch(self):
        contract = json.loads((PACKAGE / "contract.json").read_text(encoding="utf-8"))
        self.assertEqual("KEEP_CORRECT_T1A", contract["scope"]["supported_branch"])
        self.assertEqual("T1A", contract["scope"]["required_engaged_route"])
        self.assertEqual(1, contract["exact_execution_counts"]["Z_reference_total"])
        self.assertEqual(0, contract["exact_execution_counts"]["BED_MESH_CALIBRATE"])
        self.assertFalse(contract["manual_cleaning"]["automatic_brushing"])
        self.assertFalse(contract["failure_policy"]["fallback_to_stock_start"])
        self.assertEqual("8/8", contract["thermal_watchdog"]["scenario_matrix"])
        self.assertTrue(contract["thermal_watchdog"]["abort_on_non_printing_state"])
        self.assertFalse(contract["deployment_authorized"])
        self.assertFalse(contract["physical_trial"]["authorized"])
        self.assertFalse(contract["live_read_only_preflight"]["T1A_engaged"])

    def test_watchdog_scenarios_cut_heat_on_timeout_or_lost_print_state(self):
        runner = load_module("start_owner_watchdog_scenarios", "run_watchdog_scenarios.py")
        result = runner.run()
        self.assertEqual("START_OWNER_WATCHDOG_SCENARIOS_OK", result["status"])
        self.assertEqual(8, result["passed"])
        actions = {item["id"]: item["action"] for item in result["results"]}
        self.assertEqual("ABORT", actions["reference_deadline_aborts"])
        self.assertEqual("ABORT", actions["print_state_loss_aborts"])
        self.assertEqual("DISARM", actions["model_ready_disarms_without_cutting_job_heat"])

    def test_watchdog_is_armed_before_heat_and_has_a_cold_self_test(self):
        cfg = (PACKAGE / "k1-control-start-sequence-owner-v1.cfg").read_text(encoding="utf-8")
        self.assertIn("[delayed_gcode KCTRL_START_WATCHDOG_V1]", cfg)
        self.assertIn("[gcode_macro KCTRL_START_WATCHDOG_SELFTEST_V1]", cfg)
        begin = cfg.split("[gcode_macro KCTRL_JOB_BEGIN_KEEP_CORRECT_V1]", 1)[1]
        self.assertLess(begin.index("watchdog_armed VALUE=1"), begin.index("M140 S{bed}"))
        self.assertIn("TURN_OFF_HEATERS", cfg.split("[delayed_gcode KCTRL_START_WATCHDOG_V1]", 1)[1])

    def test_orca_custom_start_contains_no_stock_or_hidden_offset_command(self):
        content = (PACKAGE / "orca-start.gcode").read_text(encoding="utf-8").strip()
        self.assertTrue(content.startswith("KCTRL_JOB_BEGIN_KEEP_CORRECT_V1 "))
        self.assertNotIn("START_PRINT ", content)
        self.assertNotIn("SET_GCODE_OFFSET", content)
        self.assertNotIn(" T0", content)
        self.assertNotIn(" G28", content)

    def test_sacrificial_gcode_verifier_rejects_a_tool_select(self):
        verifier = load_module("start_owner_sacrificial", "verify_sacrificial_gcode.py")
        start = (PACKAGE / "orca-start.gcode").read_text(encoding="utf-8").strip()
        safe = "\n".join(
            [
                "; generated by OrcaSlicer 2.4.2 on 2026-08-28",
                "; total layer number: 2",
                "; max_z_height: 0.40",
                start,
                "G90",
                "; manual_filament_change = 1",
                "; post_process = ",
            ]
        )
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "safe.gcode"
            path.write_text(safe, encoding="utf-8")
            self.assertEqual(
                "START_SEQUENCE_OWNER_V1_SACRIFICIAL_GCODE_OK",
                verifier.verify(path)["status"],
            )
            path.write_text(safe + "\nT0\n", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "tool_select"):
                verifier.verify(path)

    def test_deployment_manifest_pins_every_reviewed_file(self):
        manifest = json.loads((PACKAGE / "deployment-manifest.json").read_text(encoding="utf-8"))
        self.assertEqual("PREPARED_NOT_AUTHORIZED", manifest["status"])
        self.assertFalse(manifest["deployment_authorized"])
        pins = dict(manifest["payload"])
        pins.update(manifest["reviewed_support_files"])
        for relative, expected in pins.items():
            actual = hashlib.sha256((ROOT / relative).read_bytes()).hexdigest()
            self.assertEqual(expected, actual, relative)

    def test_live_evidence_map_is_read_only_and_blocks_the_trial(self):
        evidence = json.loads((PACKAGE / "evidence-map.json").read_text(encoding="utf-8"))
        self.assertEqual("PASS_BLOCKED_NO_T1A", evidence["status"])
        self.assertEqual(0, evidence["observed"]["route_count"])
        self.assertFalse(evidence["observed"]["T1A_engaged"])
        self.assertFalse(any(evidence["effects"].values()))

    def test_python_sources_parse_as_k1_python_3_8(self):
        for name in (
            "remote_admin.py",
            "remote_jinja_validate.py",
            "watchdog_model.py",
            "run_watchdog_scenarios.py",
            "verify_sacrificial_gcode.py",
        ):
            ast.parse(
                (PACKAGE / name).read_text(encoding="utf-8"),
                filename=name,
                feature_version=(3, 8),
            )


if __name__ == "__main__":
    unittest.main()
