#!/usr/bin/env python3
"""Verify the bounded Orca export used to review START-SEQUENCE-OWNER-V1."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


EXPECTED_START = (
    "KCTRL_JOB_BEGIN_KEEP_CORRECT_V1 BED=55 PROBE_NOZZLE=140 "
    "FIRST_NOZZLE=190 PLATE=1 PROBE_REV=1 NOZZLE_ID=1 CONFIG_ID=1 "
    "X_COUNT=11 Y_COUNT=11"
)

FORBIDDEN_EXECUTABLE_PATTERNS = {
    "stock_start": re.compile(r"\b(?:START_PRINT|BOX_START_PRINT(?:_EXTRUDE_MATERIAL)?)\b", re.I),
    "stock_cleaning": re.compile(r"\b(?:CX_ROUGH_G28|CX_NOZZLE_CLEAR|NOZZLE_CLEAR)\b", re.I),
    "mesh_recalibration": re.compile(
        r"\b(?:BED_MESH_CALIBRATE|CX_PRINT_LEVELING_CALIBRATION|CHECK_BED_MESH|G29)\b",
        re.I,
    ),
    "tool_select": re.compile(r"^\s*T[0-9]+\s*$", re.I),
    "hidden_220_c": re.compile(r"^\s*M10[49]\s+S220(?:\s|$)", re.I),
    "legacy_z_offset": re.compile(r"Z_ADJUST\s*=\s*0\.27|Z_ADJUST\s+0\.27", re.I),
    "save_config": re.compile(r"\bSAVE_CONFIG\b", re.I),
}


def verify(path: Path) -> dict:
    raw = path.read_bytes()
    text = raw.decode("utf-8", errors="strict")
    lines = text.splitlines()
    executable = [line for line in lines if not line.lstrip().startswith(";")]

    start_count = sum(line.strip() == EXPECTED_START for line in executable)
    if start_count != 1:
        raise ValueError(f"expected exactly one owner start call, got {start_count}")

    forbidden_hits = []
    for number, line in enumerate(lines, start=1):
        if line.lstrip().startswith(";"):
            continue
        for name, pattern in FORBIDDEN_EXECUTABLE_PATTERNS.items():
            if pattern.search(line):
                forbidden_hits.append({"line": number, "rule": name, "text": line.strip()})
    if forbidden_hits:
        raise ValueError(f"forbidden executable G-code: {forbidden_hits}")

    layer_match = re.search(r"^; total layer number:\s*(\d+)\s*$", text, re.M)
    height_match = re.search(r"^; max_z_height:\s*([0-9.]+)\s*$", text, re.M)
    version_match = re.search(r"^; generated by OrcaSlicer ([^ ]+)", text, re.M)
    if not layer_match or int(layer_match.group(1)) > 2:
        raise ValueError("sacrificial export must contain at most two layers")
    if not height_match or float(height_match.group(1)) > 0.4:
        raise ValueError("sacrificial export exceeds the reviewed 0.4 mm height")
    if "; manual_filament_change = 1" not in text:
        raise ValueError("Orca manual_filament_change=1 proof is absent")
    if not re.search(r"^; post_process =\s*$", text, re.M):
        raise ValueError("Orca post_process is not explicitly empty")

    return {
        "status": "START_SEQUENCE_OWNER_V1_SACRIFICIAL_GCODE_OK",
        "sha256": hashlib.sha256(raw).hexdigest(),
        "bytes": len(raw),
        "orca_version": version_match.group(1) if version_match else "unknown",
        "layers": int(layer_match.group(1)),
        "max_z_mm": float(height_match.group(1)),
        "owner_start_call_count": start_count,
        "manual_filament_change": 1,
        "post_process_empty": True,
        "forbidden_executable_hits": forbidden_hits,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("gcode", type=Path)
    args = parser.parse_args()
    print(json.dumps(verify(args.gcode), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
